# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b12cda1b5581b39534e8dbfa4ddae24d"
name = "ingred-app"
handle = "ingred-app"
application_url = "https://arising-ambien-wax-audience.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "soumya8077.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_themes,write_orders,write_products,write_themes"

[auth]
redirect_urls = [
  "https://arising-ambien-wax-audience.trycloudflare.com/auth/callback",
  "https://arising-ambien-wax-audience.trycloudflare.com/auth/shopify/callback",
  "https://arising-ambien-wax-audience.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
